/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:8f16183f-b46a-4a0a-b907-b70691187129",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_INqdmycjZ",
    "aws_user_pools_web_client_id": "6uufhvd7thk5hg96fctb84cfc3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rvrvfeqvh5bedmtctoz2m7c4bi.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AWS_IAM"
};


export default awsmobile;
